### ISSUE TITLE
Installation sur Synology

### ISSUE THREAD

**Issue by jpr105** [zubrick/tv_grab_fr_telerama#1]
Bonjour,

J'utilisais jusqu'ici [tv_grab_fr_telerama](https://github.com/melmorabity/tv_grab_fr_telerama) de Mohamed El Morabity écrit en Python pour alimenter la grille des programmes TV de DVBLink. Tout ceci sur mon NAS Synology DS213+

Apparement cela ne fonctionne plus (c'est du côté Télérama d'après ce que j'ai compris), aussi je me frotte à votre script PERL. Je ne sais pas si cela va fonctionner mais j'ai commencé par installer PERL sur mon NAS et je bute sur un module absent **_use XMLTV::Usage_**.

Pourriez-vous me dire comment récupérer et installer ce module additionnel ?

Merci d'avance

Cordialement - Jean-Paul

**Comment by jpr105** [comment]
Oups, voici le message d'erreur 

> Can't locate XMLTV/Usage.pm in @INC (you may need to install the XMLTV::Usage module) (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/local/lib/perl5/vendor_perl /usr/local/share/perl5/vendor_perl /usr/local/lib/perl5/core_perl /usr/local/share/perl5/core_perl .) at tv_grab_fr_telerama.pl line 224.
BEGIN failed--compilation aborted at tv_grab_fr_telerama.pl line 224.

**Comment by zubrick** [comment]
Bonjour,

Les modules XMLTV sont disponibles sur le site de XMLTV: http://wiki.xmltv.org/index.php/Main_Page

Meilleures salutations

Zubrick

**Comment by jpr105** [comment]
Bonjour,

J'avais bien vu cette page et cette phrase :
> XMLTV is a perl module that helps to create XMLTV formatted documents. see XMLTVModule

mais le lien ne mène à rien !

En cliquant sur **_Download Info_** j'ai pas mal de choix de ressources mais là je bute un peu.

Je suis informaticien à la retraite mais n'ai pas le temps actuellement de me plonger dans PERL.
Pourriez-vous me fournir un minimum d'infos pour faire tourner votre script sous Linux Synology ... bien sûr, si cela ne vous dérange pas de trop ?

Merci d'avance
Cordialement - Jean-Paul

> cat /proc/version
Linux version 2.6.32.12 (root@build2) (gcc version 4.9.3 20150311 (prerelease) (crosstool-NG 1.20.0) ) #15152 SMP Fri Jul 14 13:18:16 CST 2017

> perl -v
This is perl 5, version 24, subversion 0 (v5.24.0) built for powerpc-linux
(with 1 registered patch, see perl -V for more detail)
Copyright 1987-2016, Larry Wall
Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.
Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by zubrick** [comment]
Bonjour,

Le lien mène au téléchargement de xmltv sous forme d'une archive dans la quelle se trouve tous les fichiers perl nécessaires. Il suffit de choisir une version à télécharger, la stable de sourceforge est bien suffisante.
Pour ce qui est de l'installation sur synology, n'en ayant pas, je ne peux pas vous aider
