### ISSUE TITLE
Duplication des champs acteur

### ISSUE THREAD

**Issue by rriv** [zubrick/tv_grab_fr_telerama#10]
Je crois que ça se comprend tout de suite sur un exemple de `<programme>` : 

```
<credits>
      <director>Alexandre Coffre (Réalisateur/Metteur en Scène)</director>
      <actor>François Damiens (David Pelame)</actor>
      <actor>Pascale Arbillot (Christine Pelame)</actor>
```
... jusque là tout va bien ...
 ... mais après nouvelle liste, qui reprend les mêmes personnes : 
```      
      <guest>François Damiens (David Pelame)</guest>
      <guest>Pascale Arbillot (Christine Pelame)</guest>
... etc
    </credits>
```

Merci

**Comment by patrick-g2** [comment]
J'ai remarqué ça aussi. 
Ça vient directement du json envoyé par le site de Télérama.
On peut voir que le rôle n'est pas le même : <actor> et <guest>.
Par exemple dans un des cas de Pascal Arbillot, pour le (télé)film "Divorces !" du 30/09, on a reçu ;
`                {
                    "id_emission": "13805718",
                    "id_personne": "46972",
                    "id_role": 2,
                    "libelle": "Interpr\u00e8te",
                    "nom": "Arbillot",
                    "ordre": "3",
                    "prenom": "Pascale",
                    "role": "Valentine",
                    "url_personnalite": "/personnalite/pascale-arbillot,9123.php"
                },
`
puis 
`                {
                    "id_emission": "13805718",
                    "id_personne": "18590",
                    "id_role": "1",
                    "libelle": "",
                    "nom": "Arbillot",
                    "ordre": "2",
                    "prenom": "Pascale",
                    "role": "Valentine",
                    "url_personnalite": "/personnalite/pascale-arbillot,9123.php"
                },
`
L'id_personne, l'id_role, le libellé ainsi que l'ordre sont différents.
Probablement des bugs dans la base de données Télérama.

C'est parfois justifié (acteur-scénariste ou acteur-réalisateur) parfois non, difficile de faire le tri.

**Comment by zubrick** [comment]
De plus, certains films n'ont aucune mention d'acteur, de réalisateur, ou même de rôle, donc un tri est assez difficile.
Je propose de clore ce cas et de se reposer sur les éditeurs du contenu de Télérama pour faire ce travail.

**Comment by zubrick** [comment]
Après analyse, et correction de l'issue #13, Je remarque que les acteurs se retrouve plusieurs fois avec le id_role 1 et le id_role 9. Il pourrait donc être possible d'ignorer les acteurs avec le id_role 9.

Une autre solution serait d'ignorer tout ce qui ne match rien et donc de ne rien mettre dans guest, car c'est souvent des doublons, mais il se peut que des fois on risque de louper des choses.

Le cas présenté par @patrick-g2 semble par contre être une erreur, car le id_role 2 est celui qui semble être attribué au réalisateur et non à un acteur qui a normalement le id_role 1.

Je sui vraiment partagé avec ça, donc je réouve le ticket et on va attendre quelques semaines pour voir si ça se règle, car pour l'instant il y a de grosses différences entre les crédits dans l'app iphone et sur le site internet, donc peut-être qu'ils sont en train de changer quelque chose.

**Comment by patrick-g2** [comment]
L'id_role = 9 c'est possiblement 'auteur'. Il y a pas mal de "petits" films/téléfilms où les acteurs sont aussi auteurs dans le sens où les dialogues sont grandement improvisés :). Plus sérieusement il arrive assez souvent que les acteurs participent aux modifications du scénario ou des dialogues. Voire même qu'ils soient carrément scénaristes. Dans la série "Père et maire" par exemple les 2 acteurs principaux ont eu l'idée originale et ont écrits pas mal d'épisodes.
L'id_role 2 apparaît aussi avec le libellé "Interprète" ce qui n'est pas loin d'acteur, est-ce que ce film est un comédie musicale ou est issu d'une pièce de théâtre ?
Voir mon commentaire dans #13.
Les doublons sont peut-être pas si délirants que ça. Il faudrait disposer de toutes les infos de prod pour confirmer ou infirmer.
Le problème c'est qu'on indique guest quand on ne connaît pas le ou les autres "rôles". Mais on a pas trop le choix.
Ah oui j'oubliais il peut y avoir plus que des doublons, dans "Sous surveillance" Robert Redford apparaît 3 fois dont 2 en guest (auteur (9) et metteur en scène (12)).

**Comment by sebastienaubry** [comment]
Ou alors il pourrait s'agir d'un champ "producteur", pour le 9 ? Il est rare et difficile de distinguer "auteur" et "scénariste".
Dans "Sous surveillance" Redford est réalisateur, producteur et acteur : http://www.imdb.com/title/tt1381404/fullcredits?ref_=tt_ov_st_sm

**Comment by patrick-g2** [comment]
Voir mon commentaire #13 : nouvelle version du grabber (en test pour l'instant, donc sur mon fork) avec entre autres une option qui permet de faciliter les investigations sur les "id_role" et les "libelle"
@sebastienaubry : 9 semble de façon assez fiable donner Auteur. 
Les json contiennent : 3 --> Scénariste ; 9 --> Auteur ; 2030 --> Scénario

**Comment by beavis69** [comment]
Wont fix with new api
