### ISSUE TITLE
category et sub-category

### ISSUE THREAD

**Issue by rriv** [zubrick/tv_grab_fr_telerama#11]
Là aussi, un exemple : 
```
    <category lang="fr">film : comédie</category>
```
J'avais l'habitude de feu http://xmltv.dtdns.net/ où le formalisme était plutôt : 
```
 <category lang="fr">film</category>
  <category lang="fr">comédie</category>
```
Ce serait envisageable ?

Merci !

**Comment by patrick-g2** [comment]
Bonjour,
C'est déjà possible depuis la version 1.30.
il faut ajouter l'option --no_aggregatecat lors de l'appel du grabber.
