### ISSUE TITLE
Disparition du réalisateur

### ISSUE THREAD

**Issue by sebastienaubry** [zubrick/tv_grab_fr_telerama#13]
Depuis peu (hier ?), le champ "director" n'est plus rempli, et les acteurs sont dans un champ "guest".
J'utilise la dernière version du script mais ce n'est pas elle qui cause ce problème, je pense.
Ce champ "director" me permet de faire le lien avec ma base de données et d'y sélectionner les films diffusés à la TV.

Exemple pour True Lies qui passe ce soir : 
```

  <programme start="20171017231500 +0200" stop="20171018015500 +0200" showview="" channel="C444.api.telerama.fr">
    <title>True Lies</title>
    <desc lang="fr">Pour une fois que les Américains réussissent un remake d'une œuvre frenchie… A partir du gentil film de Claude Zidi, &lt;I&gt; La Totale,&lt;I&gt; Cameron multiplie les scènes spectaculaires. Schwarzie, mari neuneu le jour et superman la nuit, est presque (on a dit presque) drôle. Un bon divertissement. - Critique : Film de James Cameron (USA, 1994). D'après Claude Zidi, Simon Michaël et Didier Kaminka. Image : Russell Carpenter. Musique : Brad Fiedel. 150 mn. VF. Avec Arnold Schwarzenegger : Harry Tasker. Jamie Lee Curtis : Helen Tasker. Tom Arnold : Gib. Bill Paxton : Simon. Tia Carrere : Juno Skinner. Art Malik : Salim Abu Aziz. Eliza Dushku : Dana. Charlton Heston : Spencer Trilby.
Genre : comédie d'aventures.
Depuis dix-sept ans, Harry fait croire à sa famille qu'il est un paisible représentant, alors qu'il est le super-espion d'une brigade antiterroriste. Il découvre qu'un minable, se faisant passer pour un agent secret, courtise sa femme.
Poids du budget (120 millions de dollars), choc des stars (Schwarzenegger, Jamie Lee Curtis)... C'est le remake américain d'une petite comédie bien de chez nous, La Totale, de Claude Zidi. A la caméra, James Cameron, qui n'a pas pour habitude de peser des oeufs de mouche dans des toiles d'araignée (Aliens, Abyss, Terminator - 1 et 2 - et le fameux Titanic). Surprise : le scénario imaginé par Zidi en sort bonifié ! Les scènes les plus spectaculaires se mêlent aux scènes de ménage. Pour reconquérir sa femme, Harry se livre à mille et une acrobaties aux commandes d'un hélicoptère, d'une voiture folle ou d'un avion à décollage vertical.
Déjà vu, pensez-vous ? Détrompez-vous : True Lies est le triomphe du compositing, qui consiste à incruster images de synthèse, prises de vues réelles et maquettes. Miracle de la technique, on n'y voit que du feu ! Un peu long, un peu bruyant... mais drôle et distrayant !
Bernard Génin</desc>
    <credits>
      <guest>Arnold Schwarzenegger</guest>
      <guest>Jamie Lee Curtis</guest>
      <guest>Tom Arnold</guest>
      <guest>Bill Paxton</guest>
      <guest>James Cameron (Réalisateur/Metteur en Scène)</guest>
      <guest>James Cameron</guest>
      <guest>Arnold Schwarzenegger (Harry Tasker)</guest>
      <guest>Jamie Lee Curtis (Helen Tasker)</guest>
      <guest>Tom Arnold (Albert Gibson)</guest>
      <guest>Bill Paxton (Simon)</guest>
      <guest>Charlton Heston (Spencer Trilby)</guest>
      <guest>Tia Carrere (Juno Skinner)</guest>
      <guest>Art Malik (Salim Abu Aziz)</guest>
      <guest>Eliza Dushku (Dana Tasker)</guest>
      <guest>Brad Fiedel</guest>
      <guest>James Cameron</guest>
      <guest>Claude Zidi</guest>
      <guest>Simon Michaël</guest>
      <guest>Didier Kaminka</guest>
    </credits>
    <date>1994</date>
    <category lang="fr">film</category>
    <category lang="fr">film d'action</category>
    <length units="minutes">160</length>
    <icon src="http://television.telerama.fr/sites/tr_master/files/sheet_media/media/169_emi_96265.jpg" />
    <country>américain</country>
    <star-rating>
      <value>3/5</value>
    </star-rating>
  </programme>
```

Merci

**Comment by zubrick** [comment]
Bonjour,

Il n'y a aucun réalisateur dans l'application Télérama non plus pour ce film.
Nous ne sommes pas responsable de l'exactitude et de la précision du contenu fourni par Télérama.

Meilleures salutations

**Comment by sebastienaubry** [comment]
Bonjour,

C'est une fermeture éclair :-) 

Ce sont l'ensemble des réalisateurs qui ont été perdus dans le XMLTV. Pratiquement plus aucun champ n'est renseigné dans le fichier généré pour des milliers de films, alors qu'ils étaient encore là avant-hier.

Pour l'exemple cité, le réalisateur est bien dans le JSON. Le problème est plutôt que la mention "Réalisateur/Metteur en scène" est maintenant dans le champ `role` et non `libelle`. Je vois que les autres métiers sont affectés aussi. Peut-être le champ `id_role` serait-il celui à utiliser (1 pour acteur ; 2 ou 12 pour réalisateur ou réalisateur/metteur en scène ; 12020 pour présentateur ; 4 pour compositeur ; 3 pour scénariste) ? 

```
          'intervenants' => [
                              {
                                'url_personnalite' => '/personnalite/arnold-schwarzenegger,28152.php',
                                'prenom' => 'Arnold',
                                'nom' => 'Schwarzenegger',
                                'ordre' => '1',
                                'id_emission' => '66297',
                                'role' => '',
                                'libelle' => '',
                                'id_personne' => '4896',
                                'id_role' => 1
                              },
                              {
                                'nom' => 'Lee Curtis',
                                'ordre' => '2',
                                'prenom' => 'Jamie',
                                'id_emission' => '66297',
                                'url_personnalite' => '/personnalite/jamie-lee-curtis,16730.php',
                                'id_role' => 1,
                                'role' => '',
                                'id_personne' => '3419',
                                'libelle' => ''
                              },
                              {
                                'url_personnalite' => '/personnalite/tom-arnold,17068.php',
                                'nom' => 'Arnold',
                                'ordre' => '3',
                                'prenom' => 'Tom',
                                'id_emission' => '66297',
                                'role' => '',
                                'libelle' => '',
                                'id_personne' => '42452',
                                'id_role' => 1
                              },
                              {
                                'nom' => 'Paxton',
                                'ordre' => '4',
                                'prenom' => 'Bill',
                                'id_emission' => '66297',
                                'url_personnalite' => '/personnalite/bill-paxton,29315.php',
                                'id_role' => 1,
                                'role' => '',
                                'libelle' => '',
                                'id_personne' => '7624'
                              },
                              {
                                'url_personnalite' => '/personnalite/james-cameron,10828.php',
                                'nom' => 'Cameron',
                                'ordre' => '1',
                                'prenom' => 'James',
                                'id_emission' => '66297',
                                'role' => "R\x{e9}alisateur/Metteur en Sc\x{e8}ne",
                                'libelle' => '',
                                'id_personne' => '5426',
                                'id_role' => 12
                              }, ...
```

Merci

**Comment by zubrick** [comment]
Bonjour,

Comme dit dans mon commentaire, nous ne sommes pas responsables du contenu fourni par télérama.

Si celui-ci n'est pas correcte, il n'est pas du ressort de tv_grab_fr_telerama de le corriger.

Si vous regardez par exemple "De l'autre côté du périf" ce soir vous aurez bien un réalisateur, comme pour la série tv à la même heure sur arte.

Merci donc de regarder dans l'application télérama. vous verrez que la mention "réalisateur" pour le film dont vous parlez n'est présente nulle part.

Meilleures salutations

**Comment by sebastienaubry** [comment]
Bonjour,
Je n'utilise pas l'appli télérama, uniquement tv_grab_fr_telerama. 
Sur le [site internet de Télérama](http://www.telerama.fr/cinema/films/true-lies,32963,casting.php), cette information est bien présente, de même que dans le flux JSON.
C'est peut-être juste la façon de renseigner les champs qui a changé ? Comme il n'y a pas de spécification sémantique pour ce JSON, il est difficile de parler de contenu "incorrect" s'il est présent dans le flux. Cela peut simplement être une évolution de la façon de renseigner les champs existants. Personnellement, je ne reçois pratiquement (<1%) plus aucun réalisateur depuis hier. De même, "libelle":"Acteur" n'est plus utilisé, donc ils se retrouvent tous en "Guest".

En regardant ce soir "De l'autre côté du périf", le réalisateur se retrouve là encore en "Guest" :

`      <guest>David Charhon</guest>`

Et dans le JSON : 

```
                       {
                                'url_personnalite' => '/personnalite/david-charhon,79855.php',
                                'id_role' => 2,
                                'ordre' => '1',
                                'prenom' => 'David',
                                'nom' => 'Charhon',
                                'libelle' => '',
                                'id_emission' => '43065066',
                                'id_personne' => '476841',
                                'role' => ''
                              },
```

Encore une fois, il me semberait plus propre en tout cas d'utiliser la valeur d'id_role que de tenter de parser les champs role et libelle, qui semblent moins fiables. Je peux proposer un patch en ce sens.

**Comment by zubrick** [comment]
Ok, désolé pour la réponse négative, il ne sont donc pas cohérents entre leurs deux supports.
Il semble toutefois que ce ne soit pas une généralité, et on peut trouver les deux variantes sur m6 aujourd'hui. 
J'ai ajouté une sélection basée sur le role_id si le libellé ne match aucune autre catégorie dans la version actuellement sur github.

**Comment by sebastienaubry** [comment]
Merci pour la nouvelle version. Serait-il possible d'ajouter le cas `roleid eq "12"` pour les réalisateurs/scénaristes (exemple ci-dessus) ? :

`        } elsif ($roleid eq "2" || $roleid eq "12") {`

**Comment by zubrick** [comment]
Avec ça on rejoint le cas de l'issue #10 . Il faut donc décider ce qu'on fait avec ces doublons. Arrive-t-il que le réalisateur ait uniquement l'id_role 12? j'ai l'impression que quand il y a un 12, c'est en plus du 2.

**Comment by sebastienaubry** [comment]
Je viens de regarder : dans certains cas, il y a juste le métier 12 et pas le 2. Par exemple pour l'Enlèvement au sérail vendredi prochain on a juste :
```
{
  'prenom' => 'Zabou',
  'id_emission' => '121469196',
  'role' => '',
  'nom' => 'Breitman',
  'url_personnalite' => '/personnalite/zabou-breitman,12935.php',
  'id_role' => '12',
  'ordre' => 2,
  'libelle' => "Metteur en sc\x{e8}ne",
  'id_personne' => '120777'
},

```

Je propose de simplifier le code en regroupant les tests sur `$roleid` et ceux sur `$ctype` : 
```

if ($roleid eq "1" || $ctype =~ m/Acteur/ || $ctype =~ m/Interpr.+te/ ) {
  push @{$prog{credits}{actor}}, $cname;
} elsif ($roleid eq "2" || $roleid eq "12" || $ctype =~ m/R.+alisateur/ || $ctype =~ m/Metteur en Sc.+ne/) {
  push @{$prog{credits}{director}}, $cname;
} elsif ($roleid eq "12020" || $ctype =~ m/Pr.+sentateur/ || $ctype =~ m/pr.+sentateur/) {
  push @{$prog{credits}{presenter}}, $cname;
} elsif ($roleid eq "4" || $ctype =~ m/Musique/) {
  push @{$prog{credits}{composer}}, $cname;
} elsif ($roleid eq "3" || $ctype =~ m/Cr.+ateur/ || $ctype =~ m/Auteur/ || $ctype =~ m/Sc.+nariste/ || $ctype =~ m/Sc.+nario/ || $ctype =~ m/Dialogue/) {
  push @{$prog{credits}{writer}}, $cname;
} else {
  push @{$prog{credits}{guest}}, $cname;
}
```

Et en effet, autant ne pas remettre en "guest" les acteurs déjà trouvés avec un test du style :

```
} elsif (not $cname ~~ @{$prog{credits}{actor}}) {
  push @{$prog{credits}{guest}}, $cname;
}
```

Merci

**Comment by zubrick** [comment]
dans ce cas, c'est ajouté

**Comment by patrick-g2** [comment]
Salut, c'est plus compliqué que ça.
J"ai un peu analysé une grosse centaine de json, voici ce que j'ai remarqué : 
- id_role est parfois une chaîne et parfois un entier
- le même id_code a plusieurs significations selon le type de programme.
   par exemple 15 représente "soliste" pour un opéra et "production designer" pour un film.
- Certains libellés sont identiques avec des codes différents par exemple "Image" = 16 pour un film et
   2080 pour un téléfilm.
Pour l'exemple de Zabou Breitman, si c'est un film "2" représente "Réalisateur", "12" "Metteur en scène" et "3" "Réalisateur/Metteur en scène". L'ordre vaut "2" ce qui indique probablement qu'il y a un réalisateur avec l'ordre "1" (qui est une peut-être une autre personne).
J'ai eu l'impression que lorsque le libellé est vide, c'est souvent que l'id_role a une signification différente de la "classique" (celle des films) mais que leur BD n'est pas renseignée.

Une petite liste des divers cas que j'ai rencontrés : 
[liste_role.txt](https://github.com/zubrick/tv_grab_fr_telerama/files/1384613/liste_role.txt)
Il faudrait récupérer beaucoup plus de json, sur plus de chaînes et plus de jours, et faire une analyse plus complète.

**Comment by patrick-g2** [comment]
J'ai commis une version [ici](https://raw.githubusercontent.com/patrick-g2/tv_grab_fr_telerama/master/tv_grab_fr_telerama) qui ajoute diverses choses mais qui surtout définit l'option --log_id_role qui permet de générer le fichier "log_id_role.csv" qui peut être ouvert dans Libre Office Calc ou dans Excel ou dans un éditeur quelconque.
Il contient l'id_role, le libellé, le Personnage,le Genre, l'id_genre, le genre spécifique, la Chaine et son Id. Ça évite de devoir dépouiller les json pour trouver les 

Les autres évolution sont les suivantes : 
     Complément du tag <audio>
     Ajout du titre original sous la forme  <title lang="or">Xxxxx</title>. ATTENTION certains programmes
     ont donc 2 titres, un français et un en langue originale :
            <title lang="fr">Rescue unité spéciale</title>
            <title lang="or">Rescue Special Ops</title>
     Ajout des champs <new> et <last_chance>
     Traitement plus complet du champ <premiere>
     Ajout de "use utf8" pour tenter d'éviter les problèmes d'accent dans les chaines perl.
J'ai oublié de le mettre dans le changelog mais j"ai aussi modifier le nombre maximum de jours récupéré à 14 (j'ai testé jusqu'à 13, les programme sont là)
 
On utilise le code de langue "or" (Oriya) pour version originale : ça pourrait causer un problème à un outil qui utiliserait vraiment ce champ.
La double apparition du champ <title lang=" ... pourrait aussi créer des soucis aux outils qui ne gèrent pas bien le format XMLTV.

Un exemple de fichier de log_id_role d'une quarantaine de chaine sur 13 jours : 
[log_id_role_001.zip](https://github.com/zubrick/tv_grab_fr_telerama/files/1384870/log_id_role_001.zip)
