### ISSUE TITLE
Fonctionnement 

### ISSUE THREAD

**Issue by linked67** [zubrick/tv_grab_fr_telerama#15]
Bonjour,

J'essaye de comprendre le script, surtout la partie signature.
C'est bien par exemple ça: 

    /v1/programmes/telechargement?dates=2018-01-29&nb_par_page=100&appareil=android_tablette&id_chaines=10

Qu'il faut signer avec la clé Eufea9cuweuHeif en SHA1.
Ensuite rajouter à la fin:

    &api_cle=apitel-5304b49c90511&api_signature=lasignaturesha1

Et bien sure mettre https://api.telerama.fr au début pour avoir:
    https://api.telerama.fr/v1/programmes/telechargement?dates=2018-01-29&nb_par_page=100&appareil=android_tablette&id_chaines=10&api_cle=apitel-5304b49c90511&api_signature=1449c41a5a090b84e52b7dff40fe61e29bb7f69b

Je dois avoir une faute quelque part car j'ai toujours mauvaise signature comme réponse.

**Comment by zubrick** [comment]
Bonjour,

Je penses que les ?, = et & ne font pas partie du contenu à hacher. 
La partie signature étant une contribution d'un autre utilisateur, ce n'est pas de mon ressort d'expliquer son travail, et encore moins ici.

**Comment by cnelindiahwe** [comment]
hello,
sir i am waiting for your answer please reply somthing.
