### ISSUE TITLE
Plus d'EPG depuis quelques jour

### ISSUE THREAD

**Issue by sebastienaubry** [zubrick/tv_grab_fr_telerama#16]
Bonjour,
Depuis quelques jours, je n'arrive plus à télécharger d'EPG. J'obtiens des messages d'erreur comme :

> using config filename /home/user/xmltv/tv_grab_fr_telerama.conf
> assuming default UTF-8 encoding for output
> getting listings
> Erreur 400 Bad Request en récupérant https://api.telerama.fr/v1/application/initialisation?appareil=android_tablette&api_cle=apitel-5304b49c90511&api_signature=fcbeb0383a597f2ba732f622f4b3c90e667d492d
> Seconde erreur 400 Bad Request en récupérant https://api.telerama.fr/v1/application/initialisation?appareil=android_tablette&api_cle=apitel-5304b49c90511&api_signature=fcbeb0383a597f2ba732f622f4b3c90e667d492d
> malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /path/to/xmltv/tv_grab_fr_telerama/tv_grab_fr_telerama line 879.

Auriez-vous une idée ?
Merci

**Comment by zubrick** [comment]
Bonjour,

Je n'arrives pas à reproduire votre problème.
Quelle version avez vous (tv_grab_fr_telerama --version) ?
Quels est la commande tv_grab_fr_telerama (paramètres) que vous avez utilisé pour obtenir ce résultat ?
Sous quel environnement ? 
Que se passe-t-il si vous affichez cette url dans votre navigateur?

**Comment by sebastienaubry** [comment]
Bonjour,
Cela marchait depuis des mois, et je pense n'avoir touché à rien. Je devrais être à jour car on avait regardé ensemble le ticket #11.

```
$ tv_grab_fr_telerama --version
XMLTV module version 0.5.67
This is tv_grab_fr_telerama version 1.32, 2017/10/12 18:21:00 

$ tv_grab_fr_telerama/tv_grab_fr_telerama 
using config filename /home/spontex/.xmltv/tv_grab_fr_telerama.conf
assuming default UTF-8 encoding for output
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

<tv source-info-url="https://api.telerama.fr" source-data-url="https://api.telerama.fr" generator-info-name="XMLTV" generator-info-url="http://mythtv-fr.org/">
  <channel id="C1073.api.telerama.fr">
    <display-name>BFM Business</display-name>
    <icon src="http://television.telerama.fr/sites/tr_master/files/sheet_media/tv/500x500/1073.png" />
  </channel>
  [...]
getting listings
Erreur 400 Bad Request en récupérant https://api.telerama.fr/v1/application/initialisation?appareil=android_tablette&api_signature=fcbeb0383a597f2ba732f622f4b3c90e667d492d&api_cle=apitel-5304b49c90511
Seconde erreur 400 Bad Request en récupérant https://api.telerama.fr/v1/application/initialisation?appareil=android_tablette&api_signature=fcbeb0383a597f2ba732f622f4b3c90e667d492d&api_cle=apitel-5304b49c90511
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /path/to/tv_grab_fr_telerama/tv_grab_fr_telerama line 879.
```
Je suis sous Linux Mint 18.3 Sylvia Cinnamon 64-bit.
Dans mon navigateur, j'ai également une erreur 400 Bad Request sur ces URL. Arf... avec un proxy, ça marche :-(

**Comment by zubrick** [comment]
Il semble donc qu'il s'agisse d'un problème de réseau chez vous. Je ferme ce ticket.

**Comment by sebastienaubry** [comment]
D'accord. Chez Free, certains ont-ils le même problème sur [cette URL](https://api.telerama.fr/v1/application/initialisation?appareil=android_tablette&api_signature=fcbeb0383a597f2ba732f622f4b3c90e667d492d&api_cle=apitel-5304b49c90511) ?

**Comment by sebastienaubry** [comment]
Merci. C'est résolu avec un proxy gratuit.
