### ISSUE TITLE
Died at /usr/share/perl5/vendor_perl/XMLTV.pm line 1239.

### ISSUE THREAD

**Issue by hamelg** [zubrick/tv_grab_fr_telerama#18]
Depuis quelques jours, mythfilldatabase se termine en erreur et les données disponibles s’arrêtent au 5/12 :

 ```
mythfilldatabase[31501]: E CoreContext xmltvparser.cpp:670 (parseFile) Error in 537:15: unexpected end of file
 mythfilldatabase[31501]: E CoreContext filldata.cpp:441 (GrabData) FillData: XMLTV grabber returned error code 255
```

Quand on lance tv_grab_fr_telerama à la main, il plante ici :

`Died at /usr/share/perl5/vendor_perl/XMLTV.pm line 1239.`

C'est du à des données erronées renvoyées par l'api, en l’occurrence null pour nom et prénom  :

```
         "intervenants" : [
...
            {
               "role" : "",
               "ordre" : 1,
               "url_personnalite" : "/node/5089948",
               "libelle" : "Réalisateur",
               "nom" : null,
               "id_role" : "2",
               "id_personne" : "474855",
               "id_emission" : "140871859",
              "prenom" : null
            },
...
```

EDIT:
Pour résoudre le souci j'ai du ajouter un test en ligne 1048 du tv_grab_fr_telerama :

`next unless ($cname);`

**Comment by zubrick** [comment]
Bonjour,

La version 1.33 corrige déjà cela, car ça m'est également arrivé.
Mais j'aime mieux votre façon de faire que j'ai tendance à oublier à force d'utiliser des langages où l'utilisation de next n'est pas possible, donc j'ai fait la version 1.35 dans la quel j'en ai profité pour supprimer une dépendance que j'utilise uniquement pour le debug
