### ISSUE TITLE
Error during getting listings

### ISSUE THREAD

**Issue by SylvainCecchetto** [zubrick/tv_grab_fr_telerama#21]
Hi,

Since some days the grabber don't work anymore for me, this is what I get:

```bash
getting listings: Modification of non-creatable array value attempted, subscript -1 at ./tv_grab_fr_telerama/tv_grab_fr_telerama line 988.
```

Thank you!

**Comment by beavis69** [comment]
Seems that the api doesnt work any more : it respond with a 204 No Content

I've tried the new android telerama app, and it use another api :  https://api.telerama.fr/v4/

I think the old api https://api.telerama.fr/v1/ is dead.

We need to figure out how to use the new api.

**Comment by zubrick** [comment]
Hi,

Unfortunately, my cable operator discontinued DVB-T on cable, so I had to switch to a solution that is not compatible with xmltv.
I will not be able to help you with that but feel free to do any modification, I will keep this repo open and add contributors if needed.

**Comment by beavis69** [comment]
I'm working on it, but i need time to figure out how to use api v4.

**Comment by SylvainCecchetto** [comment]
Do you have the necessary tools to trace network traffic between your Android phone and Telerama?
I have an iPhone and Charles Proxy. Maybe the iOS Telerama app also use v4 API then I can give you different traces if you want?

**Comment by beavis69** [comment]
@SylvainCecchetto yes please, it will help.
On my side i will try https://github.com/pxb1988/dex2jar on android apk to get the new signing key.

**Comment by SylvainCecchetto** [comment]
It's funny (or maybe not xD), the iOS app use a mix of API V1, V2 and V4.

You can find here some traces, if you want more traces with a specific workflow just ask me ;-)

PS: I add a filter so the traces only contains request/get with the host api.telerama.fr, so you think that some puzzle pieces are missing I can produce "full" traces.
PSS: Each trace start when I open the Telerama app on my iPhone.

Hope that will help you!

[today_now.trace.zip](https://github.com/zubrick/tv_grab_fr_telerama/files/4133370/today_now.trace.zip)
[today_per_hour_14H_16H.trace.zip](https://github.com/zubrick/tv_grab_fr_telerama/files/4133371/today_per_hour_14H_16H.trace.zip)
[programme_info.trace.zip](https://github.com/zubrick/tv_grab_fr_telerama/files/4133372/programme_info.trace.zip)
[programmes_10_fevrier.trace.zip](https://github.com/zubrick/tv_grab_fr_telerama/files/4133373/programmes_10_fevrier.trace.zip)

**Comment by beavis69** [comment]
Seems thats it's only the method telechargement from v1 which is dead.

Can you try this patch and let me know how it works for you.
It use 'grille' instead :
```
diff --git a/tv_grab_fr_telerama b/tv_grab_fr_telerama
index 83dec07..501e40f 100755
--- a/tv_grab_fr_telerama
+++ b/tv_grab_fr_telerama
@@ -409,7 +409,7 @@ $XMLTV::Get_nice::ua = LWP::UserAgent->new(
 $XMLTV::Get_nice::ua->env_proxy;
 
 $CHANNEL_GRID = '/v1/application/initialisation';
-$CHANNEL_GRID_PAGE = "/v1/programmes/telechargement";
+$CHANNEL_GRID_PAGE = "/v1/programmes/grille";
 $ROOT_URL  = 'https://api.telerama.fr';
 
 #***************************************************************************
@@ -960,9 +960,9 @@ sub process_channel_grid_all_pages ( $$$$ ) {
   my $page = 1;
   my $json_name;
   do {
-    my $url = mkurl($CHANNEL_GRID_PAGE, { 'dates' => $dayoff, 'id_chaines' => $chid, 'page' => $page });
+    my $url = mkurl($CHANNEL_GRID_PAGE, { 'date' => $dayoff, 'id_chaines' => $chid, 'nb_par_page' => 3200 });
     if ($show_url) { print STDERR $url."\n"; }
-    if ($save_json) { $jsname = mkjsonname("", { 'dates' => $dayoff, 'id_chaines' => $chid, 'page' => $page }); }
+    if ($save_json) { $jsname = mkjsonname("", { 'date' => $dayoff, 'id_chaines' => $chid, 'nb_par_page' => 3200 }); }
     $nb = process_channel_grid_page($writer, $chid, $url, $offset, $jsname, $chid_name);
     $page++;
   } until ($nb < 100);
```

Seems that there is less information available with grille method.

**Comment by GiPe66** [comment]
@beavis69 Sorry, it seems to go to endless loop when I try to get today's program with:
 /usr/local/tnt/tv_grab_fr_telerama --days 1 --offset 0

**Comment by SylvainCecchetto** [comment]
I am not able to reproduce the endless loop, for me the last commit seems to resolve the issue (I did not check concerning the programme informations details)

**Comment by GiPe66** [comment]
The problem is on Gulli channel :  channel="C482.api.telerama.fr"

To-morrow is OK.

**Comment by beavis69** [comment]
Seems to be related to channel with lots of programs per day like gulli, i'll look into it.
Got the same loop on France 4

**Comment by GiPe66** [comment]
@SylvainCecchetto  Thanks for the comment, I'll make some more tests.
@beavis69  MANY thanks for the help !!!

**Comment by GiPe66** [comment]
@beavis69 YES ! It works, Thanks a lot...

**Comment by SylvainCecchetto** [comment]
Thank you for your fix @beavis69!
In the future, if you need traces just ping me ;-)
