### ISSUE TITLE
Le grabber ne fonctionne plus

### ISSUE THREAD

**Issue by sebastienaubry** [zubrick/tv_grab_fr_telerama#22]
Bonjour,
Depuis quelques jours, alors qu'il marchait depuis des années, le grabber ne fonctionne plus avec cette erreur :
```
using config filename /home/spontex/.xmltv/tv_grab_fr_telerama.conf
assuming default UTF-8 encoding for output
getting listings
Status différent de 200, essai de nouveauStatus différent de 200, essai de nouveau
```

Merci

**Comment by beavis69** [comment]
Avez vous récupéré la dernière version ? cf #21

**Comment by sebastienaubry** [comment]
Effectivement, je n'avais pas vu cette mise à jour. Merci !
