### ISSUE TITLE
Crédits manquants

### ISSUE THREAD

**Issue by sebastienaubry** [zubrick/tv_grab_fr_telerama#23]
Bonjour,
Depuis que je suis passé de la 1.33 à la 1.36, les crédits (balise `<credits>` contenant le réalisateur...) ont apparemment disparu du fichier XML généré.
Merci

**Comment by beavis69** [comment]
On a été obligé de changer la mode d'api appellée, car l'ancienne ne fonctionnait plus.
La nouvelle api utilisée ne fourni plus ces données.
