### ISSUE TITLE
Absence de casting

### ISSUE THREAD

**Issue by andre92160** [zubrick/tv_grab_fr_telerama#24]
In the JSON received from TELERAMA some informations have disappeared. Particularly there is no more 'intervenants' which contains the whole casting of the emission.
So, I think the tv_grabber doesn't give anymore the casting.
I think we need to send another url to get this casting.
I'm interested to know what this url is.

**Comment by andre92160** [comment]
Quelqu'un a-t-il trouvé le moyen de calculer la signature dans l'url:
https://api.telerama.fr/v1/programmes/<id_programme>?api_cle=<api_cle>&api_signature=<api_signature>&appareil=<appareil>

**Comment by beavis69** [comment]
On utilise une autre api (voir #21).
Il y a plus ces infos sur la nouvelle api.

**Comment by andre92160** [comment]
J'ai lu #21. Si j'ai bien compris nous n'aurons plus le casting dans le nouveau grabber. 
Je souhaite malgré tout récupérer ponctuellement ce casting en allant le chercher sur l'URL:
https://api.telerama.fr/v1/programmes/<id_programme>?api_cle=<api_cle>&api_signature=<api_signature>&appareil=<appareil>.
Par contre je n'arrive pas à trouver sur quel string est calculé la signature.
J'ai essayé avec des choses comme:
 '/v1/programmes/appareil<appareil>programme<id_programme>'
mais je n'ai pas réussi.
As-tu le moyen de voir sur quel string l'api calcule cette signature ?

**Comment by beavis69** [comment]
Le calcul est dans la sub mkurl https://github.com/zubrick/tv_grab_fr_telerama/blob/master/tv_grab_fr_telerama#L513

Pas sûr que ce soit une bonne idée d'avoir un appel d'api supplémentaire par emisson, a minima il faut que ce soit une option à la demande.

**Comment by andre92160** [comment]
Je n'en suis pas sûr non plus, mais il semble que les n°s de programmes soient séquenciels par chaîne, donc il y aura peut-être moyen de faire une requête par chaîne.
J'ai regardé le script: dans la fonction mkurl (L513), on utilise hmac.sha1.hex avec le paramètre $u.$to_sign issu du paramètre fourni à mkurl lors de son appel à la ligne 965.
Ce paramètre comprend des éléments comme 'page' ou 'nb_par_page' qui ne sont pas ceux qui seront utilisés pour le calcul de la signature permettant d'accéder à l'url du programme. Pour cette url, ce seront des éléments comme 'programme' qui seront utilisés.
J'ai remplacé des éléments comme 'page', 'nb_par_page', ... par 'programme' avec le n° du programme mais je n'aboutis pas: je ne sais pas quels éléments l'api attend pour la signature: faut-il mettre la date ? le n° de programme doit-il être précédé par 'programme' ou 'id_programme' ou no_programme' ?
C'est là que je suis coincé.

**Comment by hamelg** [comment]
La clé est calculée avec tous les paramètres passés dans l'url. Si tu connais les paramètres à utiliser dans ta requête, il suffit d'appeler la fonction mkurl comme il faut.

**Comment by andre92160** [comment]
Tout d'abord merci de me répondre.

On accède à la grille des programmes avec des urls telles que:
"https://api.telerama.fr/v1/programmes/grille?appareil=android_tablette&api_cle=apitel-5304b49c90511&date=2020-02-03&id_chai
nes=526&nb_par_page=10000&page=1&api_signature=777c7a5686e569cd7c0eb9db767743ca5d6de1f1"

dont la signature est calculée à partir de la chaine:
"/v1/programmes/grilleappareilandroid_tablettedate2020-02-03id_chaines526nb_par_page10000page1"

Je connais l'URL permettant d'accéder au casting du programme n° 221976850: 
"https://api.telerama.fr/v1/programmes/221976850?api_cle=apitel-g4aatlgif6qzf&api_signature=1d1e228eca016407a562ef686382e7cf3aa9b155&appareil=ios_iphone"

J'ai donc supposé que la signature pour accéder à ce programme devait avoir une forme du genre:
"/v1/programmesappareilandroid_tabletteprogramme221976850"
c'est à dire en remplaçant les paramètres date, id_chaines, nb_par_page, page par le seul paramètre programme, et conservant le path et l'appareil.
Mais ça ne fonctionne pas.
Je ne suis pas certain que ces 3 paramètres (path, appareil, programme) suffisent ni que le nom du paramètre correspondant à 221976850 soit bien 'programme' plutôt que 'id_programme', 'no_programme', 'emission', ou je ne sais quoi d'autre.
Et je n'ai pas les compétences pour faire du reverse engineering sur l'api.

**Comment by hamelg** [comment]
Je pense que ton souci vient de la clé de chiffrement qui n'est pas la même :
apitel-5304b49c9051 = Euf........eif
apitel-g4aatlgif6qzf = ?

**Comment by andre92160** [comment]
Mon exemple n'était pas très clair car je donnais une url pour un 'android_tablette' et un autre pour 'ios_phone'.

J'ai fini par trouver où était le problème: le n° de programme n'était pas un paramètre comme 'date' ou 'nb_par_page. Il est partie prenante du path.
Il faut donc calculer la signature de la chaine '/v1/programmes/<n° programme>appareil<appareil>' puis faire la requête sur l'url: ' https://api.telerama.fr/v1/programmes/<n° programme>?appareil=<appareil>&api_cle=<api_cle>&api_signature=<api_signature>'

Exemple:
signature de '/v1/programmes/221976850appareilandroid_tablette' = '0f981d1c5add21b4caaf1dbac333bc74c97470ed'
url = 'https://api.telerama.fr/v1/programmes/221976850?appareil=android_tablette&api_cle=apitel-5304b49c90511&api_signature=0f981d1c5add21b4caaf1dbac333bc74c97470ed'

Ce qu'on récupère, c'est le même JSON qu'avant, donc pas de changement dans le parsing.
Par contre j'ai calculé pour une journée, ça ferait 8500 requêtes...
Une solution intermédiaire serait de ne faire la requête sur le programme que s'il s'agit d'un film (id_genre=3), ce qui réduit le nombre de requêtes à 260.

**Comment by beavis69** [comment]
Je vais ajouter cette requette avec une option du style --casting pour le faire pour les films/series uniquement.
Je regarde ça ce week-end

**Comment by GiPe66** [comment]
Merci beaucoup à vous tous. Je rejoins andre92160 pour dire que cela manquait beaucoup.

**Comment by hamelg** [comment]
Il faut faire attention de ne flooder l'api avec trop de requêtes. Si il y a de l'abus, l'usage détourné risque de se voir et des mesures pourraient être prises pour y mettre fin. Essayons de rester discret.

**Comment by andre92160** [comment]
Oui, il y a un risque évident.
Peut-être, en //,  faudrait-il proposer en téléchargement le fichier résultant ?
Romain le faisait sur MythTV, je ne sais pas si c'est encore fonctionnel.

**Comment by andre92160** [comment]
Je suis nouveau sur Github et ne connais pas son fonctionnement.
Je ne sais pas si c'est moi qui devrai clore l'issue ou l'un des collaborators ?
Et avant de clore, est-ce quelqu'un pourrait me donner quelques pistes pour savoir comment découvrir ce qu'attend l'API: quelle clé elle utilise, avec quel algorithme elle calcule sa signature, quels paramètres sont utilisés pour ce calcul, etc.
Je suppose que tout cela est lié à du reverse-engineering, mais quels outils utiliser, comment fonctionnent-ils ?
Merci.

**Comment by beavis69** [comment]
Je fermerais quand j'aurais modifié le code et fait une nouvelle release.
Pourquoi voudrais tu fermer alors que le taf n'est pas fait ?

Pour savoir comment l'api fonctionne il faut utiliser l'appli telerama sous android ou ios et enregistrer des traces de ce qu'elle fait avec un proxy https du genre https://www.charlesproxy.com/documentation/ios/ ou https://mitmproxy.org/

Pour la clef, et le calcul il faut désasembler l'appli, pour l'apk android il y a https://github.com/pxb1988/dex2jar et ensuite inspecter le code avec par exemple http://java-decompiler.github.io/

Je crois que j'ai enfin réussi à chopper la chaine de signature de la nouvelle api_cle
```
public final class a {
  private static final String[] b = new String[] { "p0Pvc6UweIUo/avpGsc3", "0gqpRpxjIu1Oj82EL4BV" };

  private final String a = b();

  private final String b() {
    String[] arrayOfString = b;
    byte b = 0;
    byte[] arrayOfByte2 = Base64.decode(arrayOfString[0], 0);
    byte[] arrayOfByte1 = Base64.decode(b[1], 0);
    byte[] arrayOfByte3 = new byte[arrayOfByte2.length];
    Intrinsics.checkExpressionValueIsNotNull(arrayOfByte1, "xorParts1");
    int i = arrayOfByte1.length;
    while (b < i) {
      arrayOfByte3[b] = (byte)(byte)(arrayOfByte2[b] ^ arrayOfByte1[b]);
      b++;
    }
    return new String(arrayOfByte3, Charsets.UTF_8);
  }
```
Ce qui en perl donnerais à peu près : 
```
#!/usr/bin/perl

use warnings;
use MIME::Base64;
my $a2 = decode_base64("p0Pvc6UweIUo/avpGsc3");
my $a1 = decode_base64("0gqpRpxjIu1Oj82EL4BV");
my $a3 = '';
my $len = length($a2);
for (my $i=0; $i <= $len; $i++) {
  {
    use bytes;
    $ca2 = ord(substr($a2,$i,1));
    $ca1 = ord(substr($a1,$i,1));
    $ca3 = $ca2 ^ $ca1;
  }
  $a3 .=chr($ca3 );
}
print $a3."\n";
```
Résultat : uIF59SZhfrfm5Gb

Je viens de tester rapidement la signature : 
```
return $ROOT_URL.$u.'?'.$params.'&api_cle=apitel-g4aatlgif6qzf&api_signature='.hmac_sha1_hex($u.$to_sign,'uIF59SZhfrfm5Gb');
```
Cela semble fonctionner, du coup on passera plus facilement sous le radar...

**Comment by andre92160** [comment]
Je n'avais pas l'intention de clore l'issue maintenant: il y avait un futur dans ma question: "Je ne sais pas si c'est moi qui **devrai** clore l'issue".
Merci pour les pistes de reverse-engineering !

**Comment by beavis69** [comment]
Je vous laisse tester la 1.37 avec l'option --casting si vous voulez le casting.

Le rôle n'est plus mis entre parenthèses, on utilise l'attribut role de <actor> pour respecter la dtd : https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd#L268

**Comment by andre92160** [comment]
tu peux aussi éliminer certaines chaines comme babytv (483): beaucoup de programmes et pas d'intervenants.

**Comment by beavis69** [comment]
C'est déja le cas car on teste aussi que $genretext eq 'Film' || $genretext eq 'Série' || $genretext eq 'Feuilleton' || $genretext eq 'Téléfilm'

**Comment by andre92160** [comment]
Oui, c'est juste que ça se passe un niveau au-dessus: tu peux savoir dès le 1er accès au site que tu n'auras pas à faire un 2nd appel, donc 1 test au lieu d'environ 340. Mais bon c'est 340 tests sans accès donc pas très couteux.
C'était juste une idée.

**Comment by beavis69** [comment]
J'ai déja passé ce grabber au profiler Devel:NYTProf et plus de 95% du temps est passé dans le telechargement et les sleeps entre chaque appel d'api.
On va pas analyser la programmation de chaque chaine pour savoir si elle passe des films ou pas...

**Comment by beavis69** [comment]
Pour avoir un ordre d'idée du coût du test : 

perl -d:NYTProf ./tv_grab_fr_telerama --casting --days 1 --output /tmp/test.xml

J'ai un fichier de conf avec 127 chaines, voici les résultats.

Profile of ./tv_grab_fr_telerama for 1674s (of 1703s), executing 20768585 statements and 5716084 subroutine calls in 221 source files and 99 string evals.

800 appels à  XMLTV::Get_nice::CORE:sleep (opcode) 1598 secondes
814470 appels | 33.4s | line | Net/HTTP/Methods.pm
711446 | 14.0s | line | IO/Socket/SSL.pm
4051111 | 5.45s | line | XML/Writer.pm
61484 | 3.99s | line | IO/Socket/IP.pm (including 1 string eval)
4394202 | 3.66s | line | XMLTV.pm
1135336 | 2.49s | line | Log/TraceMessages.pm
1139862 | 1.94s | line | IO/Handle.pm (including 1 string eval)
587284 | 1.40s | line | HTTP/Headers.pm
 
La ligne de test est appellé 4688 fois pour un temps total 28.5ms

Donc sur 1674s de temps total d'execution on passe 1598secondes à attendre pour ne pas bourinner l'api, et le test complet casting/subgenre/genretext coute 28.5ms

**Comment by GiPe66** [comment]
Ça fonctionne parfaitement chez moi. Merci à vous deux !

**Comment by andre92160** [comment]
Je n'ai pas bien compris pourquoi on passerait mieux sous le radar.
Sans doute parceque je ne sais pas trop à quoi sert apitel.
Aurais-tu une minute pour me l'expliquer sous forme vulgarisée ?

________________________________
De : beavis69 <notifications@github.com>
Envoyé : samedi 8 février 2020 02:33
À : zubrick/tv_grab_fr_telerama <tv_grab_fr_telerama@noreply.github.com>
Cc : andre92160 <andre.sune@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [zubrick/tv_grab_fr_telerama] Absence de casting (#24)


Je fermerais quand j'aurais modifié le code et fait une nouvelle release.
Pourquoi voudrais tu fermer alors que le taf n'est pas fait ?

Pour savoir comment l'api fonctionne il faut utiliser l'appli telerama sous android ou ios et enregistrer des traces de ce qu'elle fait avec un proxy https du genre https://www.charlesproxy.com/documentation/ios/<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.charlesproxy.com%2Fdocumentation%2Fios%2F&data=02%7C01%7C%7C74dec8f38ce24ce8f09808d7ac36e406%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637167224059438959&sdata=2M62Ct6GY%2Fwd8OdfM6AjqRUW7x2hlyLrIeGOqLuJXI4%3D&reserved=0> ou https://mitmproxy.org/<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmitmproxy.org%2F&data=02%7C01%7C%7C74dec8f38ce24ce8f09808d7ac36e406%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637167224059448964&sdata=FH2GIYPaJJ%2F7ajPQutDQIH1qJ%2FZQuQ%2Fz%2B2HopqMrUFo%3D&reserved=0>

Pour la clef, et le calcul il faut désasembler l'appli, pour l'apk android il y a https://github.com/pxb1988/dex2jar<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpxb1988%2Fdex2jar&data=02%7C01%7C%7C74dec8f38ce24ce8f09808d7ac36e406%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637167224059458974&sdata=i3ki%2FO%2Bxu8s4X12%2Fpiq81gOSmGIcsP6cQKJu%2F2uwZdE%3D&reserved=0> et ensuite inspecter le code avec par exemple http://java-decompiler.github.io/<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fjava-decompiler.github.io%2F&data=02%7C01%7C%7C74dec8f38ce24ce8f09808d7ac36e406%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637167224059468985&sdata=Nk0AhJtXCITIAscWdjUWzt789QjYtaRqJw%2BVwKVksNQ%3D&reserved=0>

Je crois que j'ai enfin réussi à chopper la chaine de signature de la nouvelle api_cle

public final class a {

  private static final String[] b = new String[] { "p0Pvc6UweIUo/avpGsc3", "0gqpRpxjIu1Oj82EL4BV" };



  private final String a = b();



  private final String b() {

    String[] arrayOfString = b;

    byte b = 0;

    byte[] arrayOfByte2 = Base64.decode(arrayOfString[0], 0);

    byte[] arrayOfByte1 = Base64.decode(b[1], 0);

    byte[] arrayOfByte3 = new byte[arrayOfByte2.length];

    Intrinsics.checkExpressionValueIsNotNull(arrayOfByte1, "xorParts1");

    int i = arrayOfByte1.length;

    while (b < i) {

      arrayOfByte3[b] = (byte)(byte)(arrayOfByte2[b] ^ arrayOfByte1[b]);

      b++;

    }

    return new String(arrayOfByte3, Charsets.UTF_8);

  }



Ce qui en perl donnerais à peu près :

#!/usr/bin/perl



use warnings;

use MIME::Base64;

my $a2 = decode_base64("p0Pvc6UweIUo/avpGsc3");

my $a1 = decode_base64("0gqpRpxjIu1Oj82EL4BV");

my $a3 = '';

my $len = length($a2);

for (my $i=0; $i <= $len; $i++) {

  {

    use bytes;

    $ca2 = ord(substr($a2,$i,1));

    $ca1 = ord(substr($a1,$i,1));

    $ca3 = $ca2 ^ $ca1;

  }

  $a3 .=chr($ca3 );

}

print $a3."\n";



Résultat : uIF59SZhfrfm5Gb

Je viens de tester rapidement la signature :

return $ROOT_URL.$u.'?'.$params.'&api_cle=apitel-g4aatlgif6qzf&api_signature='.hmac_sha1_hex($u.$to_sign,'uIF59SZhfrfm5Gb');



Cela semble fonctionner, du coup on passera plus facilement sous le radar...

**Comment by beavis69** [comment]
Si on utilise la dernière clef d'api la plus récente presente dans l'appli ios/android actuelle, on a moins de chance de se faire reperer qu'avec la vieille clef qui n'est plus dans les applis.

**Comment by andre92160** [comment]
OK.
J'avais espéré qu'on puisse appeler à chaque fois avec un nom d'appareil différent (lié par exemple à l'identifiant du téléphone) mais bon c'est déjà plus discret avec une clé uptodate.

________________________________
De : beavis69 <notifications@github.com>
Envoyé : dimanche 9 février 2020 16:03
À : zubrick/tv_grab_fr_telerama <tv_grab_fr_telerama@noreply.github.com>
Cc : andre92160 <andre.sune@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [zubrick/tv_grab_fr_telerama] Absence de casting (#24)


Si on utilise la dernière clef d'api la plus récente presente dans l'appli ios/android actuelle, on a moins de chance de se faire reperer qu'avec la vieille clef qui n'est plus dans les applis.
