### ISSUE TITLE
Manque le casting pour les pièces de théâtre

### ISSUE THREAD

**Issue by GiPe66** [zubrick/tv_grab_fr_telerama#25]
J'ai fait un ajout pour les pièces de théatre 

Voici le diff attaché

Merci pour vos commentaires.
[diff.zip](https://github.com/zubrick/tv_grab_fr_telerama/files/4175344/diff.zip)

**Comment by andre92160** [comment]
Merci surtout à Beavis69 !
Pour la pièce de théâtre, je ne sais pas si tu as testé avec la modif propsée ?
L'id genre de cette émission est 'null' et le genre spécifique 'pièce de théâtre.
Je ne crois pas qu'il y ait un 'id_genre' pour le théâtre.
C'est donc un test sur 'genre_spécifique' qui serait nécessaire et plutôt en recherchant la chaîne 'theat' en ignorant majuscules et accents car 'genre spécifique' semble être une zone libre (on y trouve aussi 'Theatershow'.

**Comment by andre92160** [comment]
Oh désolé ! Je n'avais pas fait vu que le test incluait 'subgenre' qui correspond à 'genre_spécifique'.

**Comment by GiPe66** [comment]
@andre92160 , oui ça fonctionne correctement  sur comedie+ avec le patch proposé, par contre je tiens compte des accents. Je peux éventuellement modifier le texte pour tester la sous chaîne sans les accents comme tu le proposes.

**Comment by andre92160** [comment]
Personnellement je fais le plus souvent mes comparaisons de chaines en les faisant passer auparavant par une fonction comme undiacritic et en ignorant la casse.

**Comment by GiPe66** [comment]
Je ne sais pas si c'est critique à ce niveau là. J'aimodifié le regexp comme ça:
`$genretext = "Théâtre" if (!$genretext && $subgenre =~ /theater|théâtre/i);`

**Comment by beavis69** [comment]
Propose ta modif dans une PR lié à ce ticket, comme ça j'ai plus qu'a commiter.

**Comment by beavis69** [comment]
Me faudrait aussi la date où vous trouvez du "Théatre" sur Comédie+

**Comment by GiPe66** [comment]
@beavis69 
Aujourd'hui 9 fev 20:55 sur comédie+, par exemple (il y a plusieurs pièces).
Je crée un pull request et je le lie à cette issue.

**Comment by beavis69** [comment]
@andre92160  Sur quelle chaîne/jour/horaire as trouvé du Theatershow ?

**Comment by GiPe66** [comment]
@beavis69 Tu es trop rapide ! J'avais tenu compte du commentaire de @andre92160 dans mon patch, mais je n'ai pas vu Theatershow.

**Comment by beavis69** [comment]
Oui désolé

J'ai récupéré toutes les chaines sur 3 jours et je n'ai pas rencontré "Theatershow"

**Comment by andre92160** [comment]
sur NPO2 (911)

________________________________
De : beavis69 <notifications@github.com>
Envoyé : dimanche 9 février 2020 13:11
À : zubrick/tv_grab_fr_telerama <tv_grab_fr_telerama@noreply.github.com>
Cc : andre92160 <andre.sune@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [zubrick/tv_grab_fr_telerama] Manque le casting pour les pièces de théâtre (#25)


@andre92160<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fandre92160&data=02%7C01%7C%7C3a11b7465cbf4f6c1e9608d7ad594158%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637168471159194942&sdata=szEZ2tIJNVzcpgXuYtbnpy7zXJbqBLHrWzfmvHjY07k%3D&reserved=0> Sur quelle chaîne/jour/horaire as trouvé du Theatershow ?

**Comment by beavis69** [comment]
Je n'en trouve pas sur NPO2, aurais tu la date, l'horaire et le titre ?

**Comment by andre92160** [comment]
En fait le plus récent est celui-ci:

                    {
                        "annee_realisation":  null,
                        "bandes_annonces":  [
                                            ],
                        "commentaires":  {
                                             "note":  0,
                                             "nb_notes":  0,
                                             "nb_commentaires":  0
                                         },
                        "critique":  "",
                        "csa":  "TP",
                        "csa_full":  [
                                         {
                                             "id_csa":  "1",
                                             "nom_court":  "TP",
                                             "nom_long":  "Tous publics"
                                         }
                                     ],
                        "flags":  {
                                      "est_clair":  false,
                                      "est_dolby":  false,
                                      "est_stereo":  false,
                                      "est_stereoar16x9":  false,
                                      "est_ar16x9":  false,
                                      "est_ar4x3":  true,
                                      "est_stm":  false,
                                      "est_vost":  false,
                                      "est_vm":  false,
                                      "est_hd":  false,
                                      "est_inedit":  false,
                                      "est_inedit_en_clair":  false,
                                      "est_inedit_crypte":  false,
                                      "est_direct":  false,
                                      "est_differe":  false,
                                      "est_resume":  false,
                                      "est_premdif":  false,
                                      "est_derdif":  false,
                                      "est_redif":  false,
                                      "est_nouveaute":  false,
                                      "est_tempsfort":  false,
                                      "est_audiovision":  false,
                                      "est_senat":  false,
                                      "est_3d":  false
                                  },
                        "genre_specifique":  "Theatershow",
                        "horaire":  {
                                        "debut":  "2018-09-04 14:35:00",
                                        "fin":  "2018-09-04 14:40:00"
                                    },
                        "id_chaine":  911,
                        "id_emission":  138978679,
                        "id_genre":  null,
                        "id_programme":  188176144,
                        "imdb":  null,
                        "libelle_nationalite":  null,
                        "note_telerama":  0,
                        "notule":  "",
                        "parties":  null,
                        "possede_bande_annonce":  false,
                        "possede_critique":  false,
                        "possede_notule":  false,
                        "prime_time":  0,
                        "replay":  null,
                        "resume":  "Improvisatieshow \u0027Vrouwennijd\u0027 met Eva Van der Gucht en Anniek Pheifer. Eva is verschrikkelijk jaloers op het geluk van vriendin Anniek en zint op wraak. \u0027Teken jij?\u0027 met Saskia Temmink en Stefan de Walle. Het is 1942. Acteurs Saskia en Stefan staan voor de keuze: Lid worden van de Kultuurkamer of geen werk meer hebben. \u0027Vega\u0027 met Yannick van de Velde en Anniek Pheifer. Het vega-eten hangt Yannick de keel uit. Hoe kan hij Anniek ervan overtuigen dat vlees gewoon lekker is?",
                        "selections":  {
                                           "films":  false,
                                           "series":  false,
                                           "replay_du_jour":  false,
                                           "plateau_tele":  false
                                       },
                        "serie":  null,
                        "showview":  "",
                        "signature":  null,
                        "signature_initiales":  "",
                        "soustitre":  "Vrouwennijd, Teken jij?, Vega",
                        "titre":  "De vloer op",
                        "titre_original":  null,
                        "url":  ""
                    },

________________________________
De : beavis69 <notifications@github.com>
Envoyé : dimanche 9 février 2020 16:04
À : zubrick/tv_grab_fr_telerama <tv_grab_fr_telerama@noreply.github.com>
Cc : andre92160 <andre.sune@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [zubrick/tv_grab_fr_telerama] Manque le casting pour les pièces de théâtre (#25)


Je n'en trouve pas sur NPO2, aurais tu la date, l'horaire et le titre ?

**Comment by beavis69** [comment]
Un json de 2018 qui utilisait l'ancienne api et qui n'avait pas déja pas d'intervenants...

**Comment by andre92160** [comment]
En fait j'ai repéré ce genre sans aller chercher s'il avait été utilisé la semaine ou l'année dernière.
J'ai le sentiment que mes suggestions ne sont pas toujours bien reçues. J'essaierai de les rendre plus rares et productives.

________________________________
De : beavis69 <notifications@github.com>
Envoyé : dimanche 9 février 2020 16:37
À : zubrick/tv_grab_fr_telerama <tv_grab_fr_telerama@noreply.github.com>
Cc : andre92160 <andre.sune@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [zubrick/tv_grab_fr_telerama] Manque le casting pour les pièces de théâtre (#25)


Un json de 2018 qui utilisait l'ancienne api et qui n'avait pas déja pas d'intervenants...

**Comment by kafifi91** [comment]
Bonjour,

Merci pour le boulot !
Petit souci lorsque je lance tv_grab_fr_telerama.pl ici :

Can't locate XMLTV/Usage.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share
/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at ./tv_grab_fr_telerama.pl line 276.
BEGIN failed--compilation aborted at ./tv_grab_fr_telerama.pl line 276.

RAS avec mon xml.pl. 
Est-ce un souci de dépendance manquante ?
Pouvez-vous m'aider svp ?

Merci.

**Comment by beavis69** [comment]
Oui probablement un problème de dépendance.
Idéalement, ouvre un nouveau ticket précise ton os, et la version que tu utilises.

**Comment by beavis69** [comment]
Et la commande que tu lances aussi.

**Comment by kafifi91** [comment]
Ci-dessous l'OS :
```
PRETTY_NAME="Debian GNU/Linux 7.0 (wheezy)"
NAME="Debian GNU/Linux"
```
et la version de Perl :
```
This is perl 5, version 14, subversion 2 (v5.14.2) 
built for x86_64-linux-gnu-thread-multi
```
J'ai lancé ceci :
`./tv_grab_fr_telerama`
et 
`./tv_grab_fr_telerama --configure`

Je ne sais comment ouvrir un ticket.

**Comment by beavis69** [comment]
Le bouton vert : new issue (en anglais)

apt-get install libxmltv-perl 
pour intaller les modules XMLTV manquants

Mais wheezy, c'est plus tout jeune, cette version n'est même plus supporté par Debian : https://wiki.debian.org/LTS 
Du coup je peux même pas vérifier ce que libxmltv-perl contient comme module sous wheezy

**Comment by kafifi91** [comment]
Tout à fait, cette machine, ma vdr box (*), est en fin de vie (je suis en train de l'upgrader : exit Wheezy, nouveau matériel + Debian Buster).

Je viens de tester sur une autre seconde machine de test plus récente :
Mint 18.3 et Perl v5.26.1.  

C'est réglé avec :

`apt install libxmltv-perl`
et 
`apt install libjson-perl`

MERCI.

(*) http://www.tvdr.de/index.htm

PS : Oups désolé je n'avais pas vu le bouton "new issue", c'est noté !

**Comment by kafifi91** [comment]
En complément.
Pour que cela fonctionne avec "--configure", il faut aussi installer cela :
`apt install libterm-readkey-perm`
