### ISSUE TITLE
Pb d'accents

### ISSUE THREAD

**Issue by loic-gouraud** [zubrick/tv_grab_fr_telerama#29]
Dans le XML, certains accents (pas tous) ne sont pas bien traités :

![drycat](https://user-images.githubusercontent.com/61745023/77918408-25087f80-729c-11ea-8152-05025e1dd044.png)

**Comment by beavis69** [comment]
Vérifie la version que tu utilise avec ```tv_grab_fr_telerama --version```

Si tu n'utilise pas la 2.2, recupère la nouvelle version et reessaye.

Si tu utilise la 2.2, peux tu attacher ton fichier xml et ton fichier de configuration, et dire avec quelles options tu lance le graber ?

**Comment by loic-gouraud** [comment]
J'étais en 2.1, j'ai upgradé en 2.2, le pb persiste. Je t'ai envoyé le debut de l'XML et le fichier .conf.

Pour les options : 
--no_htmltags
--days 11
--output /blablabla/XMLTV/tvguide_telerama.xml
--config-file /blablabla/tv_grab_fr_telerama.conf
--casting

[tvguide_telerama.zip](https://github.com/zubrick/tv_grab_fr_telerama/files/4403610/tvguide_telerama.zip)

**Comment by beavis69** [comment]
Cela vient de ton fichier de configuration qui est encodé en ISO-8859 et pas en UTF8.

Tu peux le convertir en utf8 avec iconv par exemple : 
```
cp tv_grab_fr_telerama.conf   tv_grab_fr_telerama.conf.old
iconv -f iso-8859-1 -t UTF8 tv_grab_fr_telerama.conf.old > tv_grab_fr_telerama.conf
```

**Comment by loic-gouraud** [comment]
C'est ok, encore pas au point moi avec ces encodages :).
Merci !

**Comment by beavis69** [comment]
Quand tu cherche un problème d'encodage tu peux utiliser la commande 'file'
```
file tv_grab_fr_telerama.conf.old
tv_grab_fr_telerama.conf: ISO-8859 text
```
