### ISSUE TITLE
La récupération des programmes ne fonctionne plus ?

### ISSUE THREAD

**Issue by andre92160** [zubrick/tv_grab_fr_telerama#30]
Il semble que depuis le 8 les programmes ne soient plus tous récupérés, et qu'ils ne le soient plus du tout à partir du 13.

**Comment by beavis69** [comment]
Quelle version utilisez vous ? ( --version)
Pouvez fournir votre fichier de configuration et la commande exacte que vous utiliser ?

**Comment by andre92160** [comment]
J'utilise mon propre grabber qui accède lui aussi à Télérama et selon le même principe que le votre.
Il fonctionnait correctement jusqu'à ces derniers jours.
Rencontrez-vous le même problème avec votre grabber ?

**Comment by beavis69** [comment]
Non, le grabber fonctionne normalement.

C'est quand même un peu tordu de faire une demande de support pour *votre* grabber ici, surtout que dans votre demande vous ne le préciser pas...
