### ISSUE TITLE
Offset need to be adjusted

### ISSUE THREAD

**Issue by sy6sy2** [zubrick/tv_grab_fr_telerama#31]
Hello !

Il semblerait que depuis quelques jours Telerama a fait un changement sur son site en donnant accès à moins de jours pour les programmes.

Par exemple à ce jour (09/08/20) il y a seulement les programmes jusqu'au 13/08 inclus. Quasi sûr qu'avant on pouvait aller plus loins.

Je ne sais pas si c'est pour toujours, mais si c'est le cas il faudra peut être diminuer le max de l'offset ?

Merci d'avance.

**Comment by beavis69** [comment]
Cela semble different sur l'api, il semble qu'on a les programmes jusqu'au 14/08, pas pour toutes les chaines mais pour la majorité d'entre elles.

```
-# The website is able to store at least 11 days from now
-my $default_opt_days = 11;
+# The website is able to store at least 6 days from now
+my $default_opt_days = 6;
```

```
getting listings: #############################################Aucun programme pour la chaîne 124 La Chaîne Météo le 2020-08-14
Aucun programme pour la chaîne 226 CNEWS le 2020-08-14
Aucun programme pour la chaîne 293 TéléToon+1 le 2020-08-14
Aucun programme pour la chaîne 299 Disney Channel +1 le 2020-08-14
##Aucun programme pour la chaîne 343 MCM Top le 2020-08-14
Aucun programme pour la chaîne 344 Piwi+ le 2020-08-14
Aucun programme pour la chaîne 445 C8 le 2020-08-14
Aucun programme pour la chaîne 463 OL TV le 2020-08-14
###
Aucun programme pour la chaîne 888 Nickelodéon Junior le 2020-08-14
Grabber process finished in 52 seconds for 123 chans, 25 api calls : 24 api_grille, 1 api_init, 0 cached api_casting
```

On va laisser passer une semaine pour voir si c'est temporaire ou non.

**Comment by sy6sy2** [comment]
Oui avec un peu de chance ça l'est 😉 
Tout le monde est en vacances alors ils sont peut être en mode dégradé pour l'approvisionnement des grille 😛 

Merci pour ton retour !

**Comment by beavis69** [comment]
En attendant tu peux toujours te limiter avec l'option --days 6

**Comment by beavis69** [comment]
On limite à 7 jours par defaut ( très peu de chaines n'ont que 6 jours).

On peut toujous demander 11 jours avec --days 11 mais evidement on risque de ne pas avoir de programmes pour certaines chaines.
