### ISSUE TITLE
Les credits ne sont pas lus sur un telefilm sentimental

### ISSUE THREAD

**Issue by GiPe66** [zubrick/tv_grab_fr_telerama#32]
Dans le cas du téléfilm sentimental de TF1 du 9/12 à 13:55 , les variables sont subgenre="téléfilm sentimental" et  genretext="Téléfilm"

Dans ce cas même si le opt_casting=1, les castings ne sont pas lus, voir ligne 1109 :
    if($opt_casting && ($subgenre eq '' || $subgenre !~ /(animation|réaliste|jeunesse|téléréalité|sentimental|burlesque)$/i) && ($genretext =~ /^(Film|Série|Feuilleton|Téléfilm|Théâtre)$/i)) {

le test $subgenre !~ ne valide pas le subgenre "téléfilm sentimental"

En remplaçant le !~ par =~ ça fonctionne, mais est-ce la bonne option ? Ca risque de valider trop de genres...

Merci pour ce grabber, Jean-Paul.

**Comment by beavis69** [comment]
La bonne option ce serait plutôt de retirer sentimental de l'expression régulière si vous souhaitez les castings pour ce subgenre.
On ne souhaitait pas récuperer le casting pour ce genre de programme pour éviter des appels d'api.
Honnetement, le casting des feux de l'amour c'est utile ?

**Comment by GiPe66** [comment]
Merci pour la réponse, effectivement, l'argument se tient pour les feux de l'amour, mais là il s'agit d'un téléfilm donc avec une distribution spécifique.

**Comment by beavis69** [comment]
Si vous voulez le casting pour tous les subgenres remplacer la ligne par :

**Comment by beavis69** [comment]
<pre>
if($opt_casting && $genretext =~ /^(Film|Série|Feuilleton|Téléfilm|Théâtre)$/i) {
</pre>

Ainsi vous aurez le casting quelque soit le subgenre.

Si plusieures autres personnes sont en faveur de cette modif, je ferais une nouvelle release.

**Comment by GiPe66** [comment]
Pour ma part, je pense qu'il faudrait couper la poire en deux et exclure les subgenre="feuilleton sentimental" qui n'offrent aucun intérêt, j'ai fait la modification en ce sens dans la liste des subgenre en spécifiant "telefilm\ssentimental", le résultat est correct, les téléfilms sont bien renseignés mais les feuilletons genre "feux de l'amour" ne le sont pas.

**Comment by GiPe66** [comment]
Bien sûr, il faut spécifier "feulleton\ssentimental" dans la liste d'exclusion...
