### ISSUE TITLE
progress bar already finished at /usr/local/share/perl/5.26.1/XMLTV/ProgressBar.pm line 70.

### ISSUE THREAD

**Issue by pdeliot** [zubrick/tv_grab_fr_telerama#33]
Hi,

Since 2.4 I'm facing this error:

_"progress bar already finished at /usr/local/share/perl/5.26.1/XMLTV/ProgressBar.pm line 70."_

I'm using XMLTV 0.5.70-1 under ubuntu.

Does anyone else is facing this?

**Comment by beavis69** [comment]
Hi,
Are you using 2.6 version ?
Can you attach your configuration file and paste used command-line ?

**Comment by pdeliot** [comment]
Same issue with 2.4, 2.5 and 2.6...

_tv_grab_fr_telerama --config-file /etc/xmltv/tv_grab_fr_telerama.conf  > /var/www/html/telerama.xmltv_

**Comment by beavis69** [comment]
It's fixed in 2.7

note that you'd better be using --output /var/www/html/telerama.xmltv instead of output redirection >

**Comment by pdeliot** [comment]
Looks to work.
Thanks
