### ISSUE TITLE
Problème de traitement du titre des journaux de France 3

### ISSUE THREAD

**Issue by lb544** [zubrick/tv_grab_fr_telerama#34]
Bonjour,

Merci tout d'abord pour votre travail sur l'EPG qui m'est bien utile.

J'ai juste un petit bug à remonter : Les journaux de France 3 ont leurs noms tronqués.

En effet le 12/13 Lorraine devient le 13 Lorraine ou le 12/13 : Journal National devient 13 : Journal National.

  <programme start="20210201120000 +0100" stop="20210201121800 +0100" channel="C1936.api.telerama.fr">
    <title>13 Lorraine</title>
    <category lang="fr">journal</category>
    <length units="minutes">18</length>
    <icon src="https://television.telerama.fr/sites/tr_master/files/sheet_media/media/dfe5350269f8c585516d1b3b8459e30a89a77288.jpg" />
    <rating system="CSA">
      <value>Tout public</value>
    </rating>
  </programme>
  <programme start="20210201121800 +0100" stop="20210201122500 +0100" channel="C1936.api.telerama.fr">
    <title>13 : Météo régionale</title>
    <desc lang="fr">Un aperçu des prévisions météorologiques concernant la région pour la journée et le lendemain.</desc>
    <category lang="fr">météo</category>
    <length units="minutes">7</length>
    <icon src="https://television.telerama.fr/sites/tr_master/files/sheet_media/media/e7754e458ebf632fd193c6f9cd73a6e0d370fb18.jpg" />
    <rating system="CSA">
      <value>Tout public</value>
    </rating>
  </programme>
  <programme start="20210201122500 +0100" stop="20210201125500 +0100" channel="C1936.api.telerama.fr">
    <title>13 : Journal national</title>
    <desc lang="fr">Journal national du 12/13 pour connaître l'essentiel de l'actualité nationale à la mi-journée.</desc>
    <category lang="fr">journal</category>
    <length units="minutes">30</length>
    <icon src="https://television.telerama.fr/sites/tr_master/files/sheet_media/media/646f8ede1ab01515366d7329a4a86cf69e96251e.jpg" />
    <rating system="CSA">
      <value>Tout public</value>
    </rating>
  </programme>

Alors que sur Telerama tout est OK.
![bfgmolpebapbolgc](https://user-images.githubusercontent.com/56821713/107151058-e6822d80-6960-11eb-8154-44925a6da1a7.png)

Pouvez-vous corriger le traitement du "/" ?
Merci beaucoup.

**Comment by beavis69** [comment]
Bonjour,

Il n'y a pas traitement particulier sur les / dans le titre.

Si je fais ./tv_grab_fr_telerama --days 3 --save_json --output=/tmp/test.xml et que j'inspecte le json retourné par l'api de l'application mobile telerama, le titre est déja comme ça dans le json :

**Comment by beavis69** [comment]
<pre>
         "serie" : null,
         "soustitre" : "",
         "titre" : "13 : Edition de proximité",
         "titre_original" : null,
         "url" : "https://television.telerama.fr/tele/xy/12,39479427,emission182981874.php",
</pre>

**Comment by beavis69** [comment]
D'ailleur je viens de tester sur l'appli mobile android Telerama (qui utilise la même api), le titre est aussi 13: Journal régional.

Donc ce n'est pas un problème de traitement du titre mais l'api télérama qui retourne ces titres incorrects.

**Comment by beavis69** [comment]
Je vous invite à prendre contact avec télérama pour leur remonter le problème de titre sur leur appli mobile.
S'ils corrigent les titres dans l'api pour l'appli mobile alors on aura aussi les bons titres coté grabber.
