### ISSUE TITLE
Possibilité de déactiver le triage des  chaînes

### ISSUE THREAD

**Issue by marillat** [zubrick/tv_grab_fr_telerama#35]
Bonjour,
Depuis plusieurs version (au moins la 2.5)  les chaînes sont triées alors qu'avant elles était sauvegardées dans l'ordre du fichier de configuration.
J'utilise xsltv qui génère un fichier html depuis le fichier xml du graber.
Serait-il possible d'avoir le comportement d'avant soit : suivre le tri du fichier de configuration ?
```
<tv source-info-url="https://api.telerama.fr" source-data-url="https://api.telerama.fr" generator-info-name="XMLTV" generator-info-url="http://mythtv-fr.org/">
  <channel id="C4.api.telerama.fr">
    <display-name>France 2</display-name>
    <icon src="https://television.telerama.fr/sites/tr_master/files/sheet_media/tv/500x500/4.png" />
  </channel>
  <channel id="C47.api.telerama.fr">
    <display-name>France 5</display-name>
    <icon src="https://television.telerama.fr/sites/tr_master/files/sheet_media/tv/500x500/47.png" />
  </channel>
  <channel id="C78.api.telerama.fr">
    <display-name>France 4</display-name>
    <icon src="https://television.telerama.fr/sites/tr_master/files/sheet_media/tv/500x500/78.png" />
  </channel>
```
```
channel 192 TF1;https://television.telerama.fr/sites/tr_master/files/sheet_media/tv/500x500/192.png
channel 4 France 2;https://television.telerama.fr/sites/tr_master/files/sheet_media/tv/500x500/4.png
channel 80 France 3;https://television.telerama.fr/sites/tr_master/files/sheet_media/tv/500x500/80.png
```

**Comment by beavis69** [comment]
Je vais regarder, mais les hashes ne sont pas triés par défaut en perl, l'ordre est aléatoire.
C'est pour ça que j'avais ajouté un tri sur l'id.
Je vais devoir ajouter une clef lors de la creation %channel par ordre de lecture du fichier.

**Comment by beavis69** [comment]
Je viens de releaser la version 2.8, l'ordre des chaines dans le xml est le même que dans le fichier de configuration.

**Comment by marillat** [comment]
C'est impeccable. Merci beaucoup.
