### ISSUE TITLE
Changement dans les API en 2021 ?

### ISSUE THREAD

**Issue by RT91** [zubrick/tv_grab_fr_telerama#37]
Bonjour,

Ce point a sans doute déjà été constaté : les programmes sont bien en ligne sur le site web de télérama  mais tv_grab-télérama ne semble plus récupérer les contenus à partir du mardi 5 octobre 2021 matin. (testé avec une version 6.3 et une version 6.8).

Cordialement,
     RT91

**Comment by RT91** [comment]
Pardon, je voulais écrire tv_grab_fr_telerama versions 2.3 et 2.8. Toutes mes excuses.
Cordialement,
     RT91

**Comment by beavis69** [comment]
Il ne faut pas comparer ce que récupère le grabber et le contenu du site de télérama.

La source de donnée du grabber n'est pas le site mais l'api, utilisée par les applications android/ios.

Je viens de tester l'appli et effectivement plus de programme à partir du 05/10 sur l'appli non plus.

Probablement une panne temporaire sur leur api.

On va patientez un peu pour voir s'ils réparent.

**Comment by RT91** [comment]
Bonjour,

Merci beaucoup de ce retour. Je m'étais basé sur le README de ce projet et comme je n'ai pas l'application mobile, j'avais juste vérifié le site web. Je vais m'installer l'appli pour la prochaine fois. 

Encore merci pour tout.
    RT91

**Comment by RT91** [comment]
Et l'issue peut être clos.

Cordialement,
     RT91

**Comment by RT91** [comment]
Vraiment je ne suis pas doué...

**Comment by beavis69** [comment]
Très bonne remarque, j'ai modifié le readme pour préciser que le site n'est pas la source des données de façon claire.
