### ISSUE TITLE
Barre de défilement dans l'interface utilisateur absente

### ISSUE THREAD

**Issue by Paullux** [zubrick/tv_grab_fr_telerama#4]
Bonjour,

Je viens de lancer le script avec l'option de l'interface utilisateur graphique dans une machine virtuelle, grâce à Virtualbox, le système installé est ArchLinux avec Gnome (les paramètres sont réglés par défaut).

Le bug est que la barre de défilement ne s'affiche pas, il n'y a qu'une fenêtre avec marqué "getting listings" au milieu, faut-il une dépendance particulière ?

Sur ma machine, où Arch est installé en dur, il n'y a pas le problème.

**Comment by zubrick** [comment]
L'option gui est une feature de la librairie xmltv, merci de se reporter à la documentation de xmltv pour plus d'information sur cette option.
N'ayant pas d'interface graphique, je ne l'ai jamais testée.
